# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/tower/AutoPaTa4202.proto',
  package='protoFile.tower.AutoPaTa4202',
  serialized_pb='\n\"protoFile/tower/AutoPaTa4202.proto\x12\x1cprotoFile.tower.AutoPaTa4202\"\x1d\n\x0f\x41utoPaTaRequest\x12\n\n\x02id\x18\x01 \x02(\x05\"q\n\x10\x41utoPaTaResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08\x12<\n\x0cpaTaInfoList\x18\x03 \x03(\x0b\x32&.protoFile.tower.AutoPaTa4202.PaTaInfo\"\x1b\n\x08PaTaInfo\x12\x0f\n\x07itemStr\x18\x01 \x01(\t')




_AUTOPATAREQUEST = descriptor.Descriptor(
  name='AutoPaTaRequest',
  full_name='protoFile.tower.AutoPaTa4202.AutoPaTaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.tower.AutoPaTa4202.AutoPaTaRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=97,
)


_AUTOPATARESPONSE = descriptor.Descriptor(
  name='AutoPaTaResponse',
  full_name='protoFile.tower.AutoPaTa4202.AutoPaTaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.tower.AutoPaTa4202.AutoPaTaResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.tower.AutoPaTa4202.AutoPaTaResponse.result', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='paTaInfoList', full_name='protoFile.tower.AutoPaTa4202.AutoPaTaResponse.paTaInfoList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=99,
  serialized_end=212,
)


_PATAINFO = descriptor.Descriptor(
  name='PaTaInfo',
  full_name='protoFile.tower.AutoPaTa4202.PaTaInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='itemStr', full_name='protoFile.tower.AutoPaTa4202.PaTaInfo.itemStr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=214,
  serialized_end=241,
)

_AUTOPATARESPONSE.fields_by_name['paTaInfoList'].message_type = _PATAINFO
DESCRIPTOR.message_types_by_name['AutoPaTaRequest'] = _AUTOPATAREQUEST
DESCRIPTOR.message_types_by_name['AutoPaTaResponse'] = _AUTOPATARESPONSE
DESCRIPTOR.message_types_by_name['PaTaInfo'] = _PATAINFO

class AutoPaTaRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTOPATAREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.tower.AutoPaTa4202.AutoPaTaRequest)

class AutoPaTaResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTOPATARESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.tower.AutoPaTa4202.AutoPaTaResponse)

class PaTaInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PATAINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.tower.AutoPaTa4202.PaTaInfo)

# @@protoc_insertion_point(module_scope)
