# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/skill/LoadSkill.proto',
  package='protoFile.skill.LoadSkill',
  serialized_pb='\n\x1fprotoFile/skill/LoadSkill.proto\x12\x19protoFile.skill.LoadSkill\"A\n\x10LoadSkillRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07skillId\x18\x02 \x02(\x05\x12\x10\n\x08skillPos\x18\x03 \x02(\x05\"4\n\x11LoadSkillResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_LOADSKILLREQUEST = descriptor.Descriptor(
  name='LoadSkillRequest',
  full_name='protoFile.skill.LoadSkill.LoadSkillRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.skill.LoadSkill.LoadSkillRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='skillId', full_name='protoFile.skill.LoadSkill.LoadSkillRequest.skillId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='skillPos', full_name='protoFile.skill.LoadSkill.LoadSkillRequest.skillPos', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=62,
  serialized_end=127,
)


_LOADSKILLRESPONSE = descriptor.Descriptor(
  name='LoadSkillResponse',
  full_name='protoFile.skill.LoadSkill.LoadSkillResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.skill.LoadSkill.LoadSkillResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.skill.LoadSkill.LoadSkillResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=129,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['LoadSkillRequest'] = _LOADSKILLREQUEST
DESCRIPTOR.message_types_by_name['LoadSkillResponse'] = _LOADSKILLRESPONSE

class LoadSkillRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOADSKILLREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.skill.LoadSkill.LoadSkillRequest)

class LoadSkillResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOADSKILLRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.skill.LoadSkill.LoadSkillResponse)

# @@protoc_insertion_point(module_scope)
