# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import app.scense.protoFile.pet.petInfo_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/pet/GetBeiJiChengList2313.proto',
  package='protoFile.pet.GetBeiJiChengList2313',
  serialized_pb='\n)protoFile/pet/GetBeiJiChengList2313.proto\x12#protoFile.pet.GetBeiJiChengList2313\x1a\x1bprotoFile/pet/petInfo.proto\"5\n\x18GetBeiJiChengListRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05petId\x18\x02 \x02(\x05\"\x83\x01\n\x19GetBeiJiChengListResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x45\n\x0bpetInfoList\x18\x03 \x03(\x0b\x32\x30.protoFile.pet.GetBeiJiChengList2313.PetInfoList\"D\n\x0bPetInfoList\x12\x0f\n\x07reqCoin\x18\x01 \x01(\x05\x12$\n\x04info\x18\x02 \x01(\x0b\x32\x16.protoFile.pet.PetInfo')




_GETBEIJICHENGLISTREQUEST = descriptor.Descriptor(
  name='GetBeiJiChengListRequest',
  full_name='protoFile.pet.GetBeiJiChengList2313.GetBeiJiChengListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.pet.GetBeiJiChengList2313.GetBeiJiChengListRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='petId', full_name='protoFile.pet.GetBeiJiChengList2313.GetBeiJiChengListRequest.petId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=111,
  serialized_end=164,
)


_GETBEIJICHENGLISTRESPONSE = descriptor.Descriptor(
  name='GetBeiJiChengListResponse',
  full_name='protoFile.pet.GetBeiJiChengList2313.GetBeiJiChengListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.pet.GetBeiJiChengList2313.GetBeiJiChengListResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.pet.GetBeiJiChengList2313.GetBeiJiChengListResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='petInfoList', full_name='protoFile.pet.GetBeiJiChengList2313.GetBeiJiChengListResponse.petInfoList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=167,
  serialized_end=298,
)


_PETINFOLIST = descriptor.Descriptor(
  name='PetInfoList',
  full_name='protoFile.pet.GetBeiJiChengList2313.PetInfoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='reqCoin', full_name='protoFile.pet.GetBeiJiChengList2313.PetInfoList.reqCoin', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='info', full_name='protoFile.pet.GetBeiJiChengList2313.PetInfoList.info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=300,
  serialized_end=368,
)

_GETBEIJICHENGLISTRESPONSE.fields_by_name['petInfoList'].message_type = _PETINFOLIST
_PETINFOLIST.fields_by_name['info'].message_type = app.scense.protoFile.pet.petInfo_pb2._PETINFO
DESCRIPTOR.message_types_by_name['GetBeiJiChengListRequest'] = _GETBEIJICHENGLISTREQUEST
DESCRIPTOR.message_types_by_name['GetBeiJiChengListResponse'] = _GETBEIJICHENGLISTRESPONSE
DESCRIPTOR.message_types_by_name['PetInfoList'] = _PETINFOLIST

class GetBeiJiChengListRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETBEIJICHENGLISTREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.pet.GetBeiJiChengList2313.GetBeiJiChengListRequest)

class GetBeiJiChengListResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETBEIJICHENGLISTRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.pet.GetBeiJiChengList2313.GetBeiJiChengListResponse)

class PetInfoList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PETINFOLIST
  
  # @@protoc_insertion_point(class_scope:protoFile.pet.GetBeiJiChengList2313.PetInfoList)

# @@protoc_insertion_point(module_scope)
