# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/pet/PetChuanCheng2314.proto',
  package='protoFile.pet.PetChuanCheng2314',
  serialized_pb='\n%protoFile/pet/PetChuanCheng2314.proto\x12\x1fprotoFile.pet.PetChuanCheng2314\"C\n\x14PetChuanChengRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05petId\x18\x02 \x02(\x05\x12\x10\n\x08\x62jcPetId\x18\x03 \x02(\x05\"8\n\x15PetChuanChengResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08')




_PETCHUANCHENGREQUEST = descriptor.Descriptor(
  name='PetChuanChengRequest',
  full_name='protoFile.pet.PetChuanCheng2314.PetChuanChengRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.pet.PetChuanCheng2314.PetChuanChengRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='petId', full_name='protoFile.pet.PetChuanCheng2314.PetChuanChengRequest.petId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bjcPetId', full_name='protoFile.pet.PetChuanCheng2314.PetChuanChengRequest.bjcPetId', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=141,
)


_PETCHUANCHENGRESPONSE = descriptor.Descriptor(
  name='PetChuanChengResponse',
  full_name='protoFile.pet.PetChuanCheng2314.PetChuanChengResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.pet.PetChuanCheng2314.PetChuanChengResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.pet.PetChuanCheng2314.PetChuanChengResponse.result', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=143,
  serialized_end=199,
)

DESCRIPTOR.message_types_by_name['PetChuanChengRequest'] = _PETCHUANCHENGREQUEST
DESCRIPTOR.message_types_by_name['PetChuanChengResponse'] = _PETCHUANCHENGRESPONSE

class PetChuanChengRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PETCHUANCHENGREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.pet.PetChuanCheng2314.PetChuanChengRequest)

class PetChuanChengResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PETCHUANCHENGRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.pet.PetChuanCheng2314.PetChuanChengResponse)

# @@protoc_insertion_point(module_scope)
