# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/strengthen/GetNextLevelItemInfo2117.proto',
  package='protoFile.strengthen.GetNextLevelItemInfo2117',
  serialized_pb='\n3protoFile/strengthen/GetNextLevelItemInfo2117.proto\x12-protoFile.strengthen.GetNextLevelItemInfo2117\"9\n\x1bGetNextLevelItemInfoRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06itemId\x18\x02 \x02(\x05\"\x8a\x01\n\x1cGetNextLevelItemInfoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08\x12I\n\x08nextInfo\x18\x03 \x01(\x0b\x32\x37.protoFile.strengthen.GetNextLevelItemInfo2117.NextInfo\"o\n\x08NextInfo\x12\x0e\n\x06itemId\x18\x01 \x01(\x05\x12\x0e\n\x06strEff\x18\x02 \x01(\t\x12\x10\n\x08\x65\x66\x66Value\x18\x03 \x01(\t\x12\x0f\n\x07reqCoin\x18\x04 \x01(\x05\x12\x0f\n\x07mubanid\x18\x05 \x01(\x05\x12\x0f\n\x07qhlevel\x18\x06 \x01(\x05')




_GETNEXTLEVELITEMINFOREQUEST = descriptor.Descriptor(
  name='GetNextLevelItemInfoRequest',
  full_name='protoFile.strengthen.GetNextLevelItemInfo2117.GetNextLevelItemInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.strengthen.GetNextLevelItemInfo2117.GetNextLevelItemInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='itemId', full_name='protoFile.strengthen.GetNextLevelItemInfo2117.GetNextLevelItemInfoRequest.itemId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=102,
  serialized_end=159,
)


_GETNEXTLEVELITEMINFORESPONSE = descriptor.Descriptor(
  name='GetNextLevelItemInfoResponse',
  full_name='protoFile.strengthen.GetNextLevelItemInfo2117.GetNextLevelItemInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.strengthen.GetNextLevelItemInfo2117.GetNextLevelItemInfoResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.strengthen.GetNextLevelItemInfo2117.GetNextLevelItemInfoResponse.result', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nextInfo', full_name='protoFile.strengthen.GetNextLevelItemInfo2117.GetNextLevelItemInfoResponse.nextInfo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=162,
  serialized_end=300,
)


_NEXTINFO = descriptor.Descriptor(
  name='NextInfo',
  full_name='protoFile.strengthen.GetNextLevelItemInfo2117.NextInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='itemId', full_name='protoFile.strengthen.GetNextLevelItemInfo2117.NextInfo.itemId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='strEff', full_name='protoFile.strengthen.GetNextLevelItemInfo2117.NextInfo.strEff', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='effValue', full_name='protoFile.strengthen.GetNextLevelItemInfo2117.NextInfo.effValue', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reqCoin', full_name='protoFile.strengthen.GetNextLevelItemInfo2117.NextInfo.reqCoin', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mubanid', full_name='protoFile.strengthen.GetNextLevelItemInfo2117.NextInfo.mubanid', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='qhlevel', full_name='protoFile.strengthen.GetNextLevelItemInfo2117.NextInfo.qhlevel', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=302,
  serialized_end=413,
)

_GETNEXTLEVELITEMINFORESPONSE.fields_by_name['nextInfo'].message_type = _NEXTINFO
DESCRIPTOR.message_types_by_name['GetNextLevelItemInfoRequest'] = _GETNEXTLEVELITEMINFOREQUEST
DESCRIPTOR.message_types_by_name['GetNextLevelItemInfoResponse'] = _GETNEXTLEVELITEMINFORESPONSE
DESCRIPTOR.message_types_by_name['NextInfo'] = _NEXTINFO

class GetNextLevelItemInfoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETNEXTLEVELITEMINFOREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.strengthen.GetNextLevelItemInfo2117.GetNextLevelItemInfoRequest)

class GetNextLevelItemInfoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETNEXTLEVELITEMINFORESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.strengthen.GetNextLevelItemInfo2117.GetNextLevelItemInfoResponse)

class NextInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEXTINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.strengthen.GetNextLevelItemInfo2117.NextInfo)

# @@protoc_insertion_point(module_scope)
