# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/strengthen/StrengthenItem2102.proto',
  package='protoFile.strengthen.StrengthenItem2102',
  serialized_pb='\n-protoFile/strengthen/StrengthenItem2102.proto\x12\'protoFile.strengthen.StrengthenItem2102\"3\n\x15StrengthenItemRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06itemId\x18\x02 \x02(\x05\"9\n\x16StrengthenItemResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_STRENGTHENITEMREQUEST = descriptor.Descriptor(
  name='StrengthenItemRequest',
  full_name='protoFile.strengthen.StrengthenItem2102.StrengthenItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.strengthen.StrengthenItem2102.StrengthenItemRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='itemId', full_name='protoFile.strengthen.StrengthenItem2102.StrengthenItemRequest.itemId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=90,
  serialized_end=141,
)


_STRENGTHENITEMRESPONSE = descriptor.Descriptor(
  name='StrengthenItemResponse',
  full_name='protoFile.strengthen.StrengthenItem2102.StrengthenItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.strengthen.StrengthenItem2102.StrengthenItemResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.strengthen.StrengthenItem2102.StrengthenItemResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=143,
  serialized_end=200,
)

DESCRIPTOR.message_types_by_name['StrengthenItemRequest'] = _STRENGTHENITEMREQUEST
DESCRIPTOR.message_types_by_name['StrengthenItemResponse'] = _STRENGTHENITEMRESPONSE

class StrengthenItemRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRENGTHENITEMREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.strengthen.StrengthenItem2102.StrengthenItemRequest)

class StrengthenItemResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRENGTHENITEMRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.strengthen.StrengthenItem2102.StrengthenItemResponse)

# @@protoc_insertion_point(module_scope)
