# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/PromptedMessage.proto',
  package='protoFile.PromptedMessage',
  serialized_pb='\n\x1fprotoFile/PromptedMessage.proto\x12\x19protoFile.PromptedMessage\"#\n\x0fPromptedMessage\x12\x10\n\x08prompted\x18\x01 \x02(\t')




_PROMPTEDMESSAGE = descriptor.Descriptor(
  name='PromptedMessage',
  full_name='protoFile.PromptedMessage.PromptedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='prompted', full_name='protoFile.PromptedMessage.PromptedMessage.prompted', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=62,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['PromptedMessage'] = _PROMPTEDMESSAGE

class PromptedMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROMPTEDMESSAGE
  
  # @@protoc_insertion_point(class_scope:protoFile.PromptedMessage.PromptedMessage)

# @@protoc_insertion_point(module_scope)
