# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/arena/JingJiCleanCD_2705.proto',
  package='protoFile.arena.JingJiCleanCD_2705',
  serialized_pb='\n(protoFile/arena/JingJiCleanCD_2705.proto\x12\"protoFile.arena.JingJiCleanCD_2705\"\"\n\x14JingjiCleanCDRequest\x12\n\n\x02id\x18\x01 \x02(\x05\"8\n\x15JingjiCleanCDResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_JINGJICLEANCDREQUEST = descriptor.Descriptor(
  name='JingjiCleanCDRequest',
  full_name='protoFile.arena.JingJiCleanCD_2705.JingjiCleanCDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.arena.JingJiCleanCD_2705.JingjiCleanCDRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=80,
  serialized_end=114,
)


_JINGJICLEANCDRESPONSE = descriptor.Descriptor(
  name='JingjiCleanCDResponse',
  full_name='protoFile.arena.JingJiCleanCD_2705.JingjiCleanCDResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.arena.JingJiCleanCD_2705.JingjiCleanCDResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.arena.JingJiCleanCD_2705.JingjiCleanCDResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=116,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['JingjiCleanCDRequest'] = _JINGJICLEANCDREQUEST
DESCRIPTOR.message_types_by_name['JingjiCleanCDResponse'] = _JINGJICLEANCDRESPONSE

class JingjiCleanCDRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JINGJICLEANCDREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.arena.JingJiCleanCD_2705.JingjiCleanCDRequest)

class JingjiCleanCDResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JINGJICLEANCDRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.arena.JingJiCleanCD_2705.JingjiCleanCDResponse)

# @@protoc_insertion_point(module_scope)
