# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/team/invitedGroup.proto',
  package='protoFile.team.invitedGroup',
  serialized_pb='\n!protoFile/team/invitedGroup.proto\x12\x1bprotoFile.team.invitedGroup\".\n\x13invitedGroupRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0b\n\x03tid\x18\x02 \x02(\x05\"E\n\x14invitedGroupResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t')




_INVITEDGROUPREQUEST = descriptor.Descriptor(
  name='invitedGroupRequest',
  full_name='protoFile.team.invitedGroup.invitedGroupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.team.invitedGroup.invitedGroupRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tid', full_name='protoFile.team.invitedGroup.invitedGroupRequest.tid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=112,
)


_INVITEDGROUPRESPONSE = descriptor.Descriptor(
  name='invitedGroupResponse',
  full_name='protoFile.team.invitedGroup.invitedGroupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.team.invitedGroup.invitedGroupResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.team.invitedGroup.invitedGroupResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='protoFile.team.invitedGroup.invitedGroupResponse.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=114,
  serialized_end=183,
)

DESCRIPTOR.message_types_by_name['invitedGroupRequest'] = _INVITEDGROUPREQUEST
DESCRIPTOR.message_types_by_name['invitedGroupResponse'] = _INVITEDGROUPRESPONSE

class invitedGroupRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVITEDGROUPREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.team.invitedGroup.invitedGroupRequest)

class invitedGroupResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVITEDGROUPRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.team.invitedGroup.invitedGroupResponse)

# @@protoc_insertion_point(module_scope)
