# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/team/pushTeamMemberInfo.proto',
  package='protoFile.team.pushTeamMemberInfo',
  serialized_pb='\n\'protoFile/team/pushTeamMemberInfo.proto\x12!protoFile.team.pushTeamMemberInfo\"a\n\x0eTeamMemberInfo\x12=\n\x06member\x18\x01 \x03(\x0b\x32-.protoFile.team.pushTeamMemberInfo.memberInfo\x12\x10\n\x08leaderId\x18\x02 \x02(\x05\"\x83\x01\n\nmemberInfo\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x10\n\x08nickname\x18\x02 \x02(\t\x12\r\n\x05level\x18\x03 \x02(\x05\x12\x12\n\nprofession\x18\x04 \x02(\x05\x12\r\n\x05maxHp\x18\x05 \x02(\x05\x12\n\n\x02hp\x18\x06 \x02(\x05\x12\r\n\x05maxMp\x18\x07 \x02(\x05\x12\n\n\x02mp\x18\x08 \x02(\x05')




_TEAMMEMBERINFO = descriptor.Descriptor(
  name='TeamMemberInfo',
  full_name='protoFile.team.pushTeamMemberInfo.TeamMemberInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='member', full_name='protoFile.team.pushTeamMemberInfo.TeamMemberInfo.member', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='leaderId', full_name='protoFile.team.pushTeamMemberInfo.TeamMemberInfo.leaderId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=175,
)


_MEMBERINFO = descriptor.Descriptor(
  name='memberInfo',
  full_name='protoFile.team.pushTeamMemberInfo.memberInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.team.pushTeamMemberInfo.memberInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nickname', full_name='protoFile.team.pushTeamMemberInfo.memberInfo.nickname', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='level', full_name='protoFile.team.pushTeamMemberInfo.memberInfo.level', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='profession', full_name='protoFile.team.pushTeamMemberInfo.memberInfo.profession', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='maxHp', full_name='protoFile.team.pushTeamMemberInfo.memberInfo.maxHp', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hp', full_name='protoFile.team.pushTeamMemberInfo.memberInfo.hp', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='maxMp', full_name='protoFile.team.pushTeamMemberInfo.memberInfo.maxMp', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mp', full_name='protoFile.team.pushTeamMemberInfo.memberInfo.mp', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=178,
  serialized_end=309,
)

_TEAMMEMBERINFO.fields_by_name['member'].message_type = _MEMBERINFO
DESCRIPTOR.message_types_by_name['TeamMemberInfo'] = _TEAMMEMBERINFO
DESCRIPTOR.message_types_by_name['memberInfo'] = _MEMBERINFO

class TeamMemberInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEAMMEMBERINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.team.pushTeamMemberInfo.TeamMemberInfo)

class memberInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMBERINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.team.pushTeamMemberInfo.memberInfo)

# @@protoc_insertion_point(module_scope)
