# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/shop/NpcShopSellItem220.proto',
  package='protoFile.shop.NpcShopSellItem220',
  serialized_pb='\n\'protoFile/shop/NpcShopSellItem220.proto\x12!protoFile.shop.NpcShopSellItem220\"n\n\x16npcShopSellItemRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07itemPos\x18\x02 \x02(\x05\x12\x13\n\x0bpackageType\x18\x03 \x02(\x05\x12\x0f\n\x07\x63urpage\x18\x04 \x02(\x05\x12\x11\n\tsellCount\x18\x05 \x02(\x05\"y\n\x17npcShopSellItemResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12=\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32/.protoFile.shop.NpcShopSellItem220.ResponseData\"4\n\x0cResponseData\x12\x13\n\x0bpackageType\x18\x01 \x01(\x05\x12\x0f\n\x07\x63urpage\x18\x02 \x01(\x05')




_NPCSHOPSELLITEMREQUEST = descriptor.Descriptor(
  name='npcShopSellItemRequest',
  full_name='protoFile.shop.NpcShopSellItem220.npcShopSellItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.shop.NpcShopSellItem220.npcShopSellItemRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='itemPos', full_name='protoFile.shop.NpcShopSellItem220.npcShopSellItemRequest.itemPos', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='packageType', full_name='protoFile.shop.NpcShopSellItem220.npcShopSellItemRequest.packageType', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='curpage', full_name='protoFile.shop.NpcShopSellItem220.npcShopSellItemRequest.curpage', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sellCount', full_name='protoFile.shop.NpcShopSellItem220.npcShopSellItemRequest.sellCount', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=188,
)


_NPCSHOPSELLITEMRESPONSE = descriptor.Descriptor(
  name='npcShopSellItemResponse',
  full_name='protoFile.shop.NpcShopSellItem220.npcShopSellItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.shop.NpcShopSellItem220.npcShopSellItemResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.shop.NpcShopSellItem220.npcShopSellItemResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='protoFile.shop.NpcShopSellItem220.npcShopSellItemResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=190,
  serialized_end=311,
)


_RESPONSEDATA = descriptor.Descriptor(
  name='ResponseData',
  full_name='protoFile.shop.NpcShopSellItem220.ResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='packageType', full_name='protoFile.shop.NpcShopSellItem220.ResponseData.packageType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='curpage', full_name='protoFile.shop.NpcShopSellItem220.ResponseData.curpage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=313,
  serialized_end=365,
)

_NPCSHOPSELLITEMRESPONSE.fields_by_name['data'].message_type = _RESPONSEDATA
DESCRIPTOR.message_types_by_name['npcShopSellItemRequest'] = _NPCSHOPSELLITEMREQUEST
DESCRIPTOR.message_types_by_name['npcShopSellItemResponse'] = _NPCSHOPSELLITEMRESPONSE
DESCRIPTOR.message_types_by_name['ResponseData'] = _RESPONSEDATA

class npcShopSellItemRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NPCSHOPSELLITEMREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.shop.NpcShopSellItem220.npcShopSellItemRequest)

class npcShopSellItemResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NPCSHOPSELLITEMRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.shop.NpcShopSellItem220.npcShopSellItemResponse)

class ResponseData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSEDATA
  
  # @@protoc_insertion_point(class_scope:protoFile.shop.NpcShopSellItem220.ResponseData)

# @@protoc_insertion_point(module_scope)
