# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/chat/CloseChatWindow1014.proto',
  package='protoFile.chat.CloseChatWindow1014',
  serialized_pb='\n(protoFile/chat/CloseChatWindow1014.proto\x12\"protoFile.chat.CloseChatWindow1014\"$\n\x16\x43loseChatWindowRequest\x12\n\n\x02id\x18\x01 \x02(\x05\":\n\x17\x43loseChatWindowResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_CLOSECHATWINDOWREQUEST = descriptor.Descriptor(
  name='CloseChatWindowRequest',
  full_name='protoFile.chat.CloseChatWindow1014.CloseChatWindowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.chat.CloseChatWindow1014.CloseChatWindowRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=80,
  serialized_end=116,
)


_CLOSECHATWINDOWRESPONSE = descriptor.Descriptor(
  name='CloseChatWindowResponse',
  full_name='protoFile.chat.CloseChatWindow1014.CloseChatWindowResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.chat.CloseChatWindow1014.CloseChatWindowResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.chat.CloseChatWindow1014.CloseChatWindowResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=118,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['CloseChatWindowRequest'] = _CLOSECHATWINDOWREQUEST
DESCRIPTOR.message_types_by_name['CloseChatWindowResponse'] = _CLOSECHATWINDOWRESPONSE

class CloseChatWindowRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLOSECHATWINDOWREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.chat.CloseChatWindow1014.CloseChatWindowRequest)

class CloseChatWindowResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLOSECHATWINDOWRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.chat.CloseChatWindow1014.CloseChatWindowResponse)

# @@protoc_insertion_point(module_scope)
