# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/fight/TurnOneCard.proto',
  package='protoFile.fight.TurnOneCard',
  serialized_pb='\n!protoFile/fight/TurnOneCard.proto\x12\x1bprotoFile.fight.TurnOneCard\"D\n\x0bTurnOneCard\x12\x13\n\x0b\x63haracterId\x18\x01 \x02(\x05\x12\x10\n\x08nickname\x18\x02 \x02(\t\x12\x0e\n\x06\x63\x61rdId\x18\x03 \x02(\x05')




_TURNONECARD = descriptor.Descriptor(
  name='TurnOneCard',
  full_name='protoFile.fight.TurnOneCard.TurnOneCard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='characterId', full_name='protoFile.fight.TurnOneCard.TurnOneCard.characterId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nickname', full_name='protoFile.fight.TurnOneCard.TurnOneCard.nickname', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cardId', full_name='protoFile.fight.TurnOneCard.TurnOneCard.cardId', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['TurnOneCard'] = _TURNONECARD

class TurnOneCard(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TURNONECARD
  
  # @@protoc_insertion_point(class_scope:protoFile.fight.TurnOneCard.TurnOneCard)

# @@protoc_insertion_point(module_scope)
