# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/hall/GetUserOrFriendsListInfo.proto',
  package='protoFile.hall.GetUserOrFriendsListInfo',
  serialized_pb='\n-protoFile/hall/GetUserOrFriendsListInfo.proto\x12\'protoFile.hall.GetUserOrFriendsListInfo\"P\n\x1fGetUserOrFriendsListInfoRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07\x63urPage\x18\x02 \x02(\x05\x12\x10\n\x08\x64\x61taType\x18\x03 \x02(\x05\"\x91\x01\n GetUserOrFriendsListInfoResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12L\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32>.protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendsListInfo\"\x8e\x01\n\x15UserOrFriendsListInfo\x12S\n\x10userOrFriendInfo\x18\x01 \x03(\x0b\x32\x39.protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendInfo\x12\x0f\n\x07maxPage\x18\x02 \x01(\x05\x12\x0f\n\x07\x63urPage\x18\x03 \x01(\x05\"_\n\x10UserOrFriendInfo\x12\x0e\n\x06roleId\x18\x01 \x01(\x05\x12\x11\n\troleLevel\x18\x02 \x01(\x05\x12\x10\n\x08roleName\x18\x03 \x01(\t\x12\x16\n\x0eroleProfession\x18\x04 \x01(\x05')




_GETUSERORFRIENDSLISTINFOREQUEST = descriptor.Descriptor(
  name='GetUserOrFriendsListInfoRequest',
  full_name='protoFile.hall.GetUserOrFriendsListInfo.GetUserOrFriendsListInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.hall.GetUserOrFriendsListInfo.GetUserOrFriendsListInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='curPage', full_name='protoFile.hall.GetUserOrFriendsListInfo.GetUserOrFriendsListInfoRequest.curPage', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dataType', full_name='protoFile.hall.GetUserOrFriendsListInfo.GetUserOrFriendsListInfoRequest.dataType', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=90,
  serialized_end=170,
)


_GETUSERORFRIENDSLISTINFORESPONSE = descriptor.Descriptor(
  name='GetUserOrFriendsListInfoResponse',
  full_name='protoFile.hall.GetUserOrFriendsListInfo.GetUserOrFriendsListInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.hall.GetUserOrFriendsListInfo.GetUserOrFriendsListInfoResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.hall.GetUserOrFriendsListInfo.GetUserOrFriendsListInfoResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='protoFile.hall.GetUserOrFriendsListInfo.GetUserOrFriendsListInfoResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=173,
  serialized_end=318,
)


_USERORFRIENDSLISTINFO = descriptor.Descriptor(
  name='UserOrFriendsListInfo',
  full_name='protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendsListInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userOrFriendInfo', full_name='protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendsListInfo.userOrFriendInfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='maxPage', full_name='protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendsListInfo.maxPage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='curPage', full_name='protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendsListInfo.curPage', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=321,
  serialized_end=463,
)


_USERORFRIENDINFO = descriptor.Descriptor(
  name='UserOrFriendInfo',
  full_name='protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='roleId', full_name='protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendInfo.roleId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roleLevel', full_name='protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendInfo.roleLevel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roleName', full_name='protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendInfo.roleName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roleProfession', full_name='protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendInfo.roleProfession', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=465,
  serialized_end=560,
)

_GETUSERORFRIENDSLISTINFORESPONSE.fields_by_name['data'].message_type = _USERORFRIENDSLISTINFO
_USERORFRIENDSLISTINFO.fields_by_name['userOrFriendInfo'].message_type = _USERORFRIENDINFO
DESCRIPTOR.message_types_by_name['GetUserOrFriendsListInfoRequest'] = _GETUSERORFRIENDSLISTINFOREQUEST
DESCRIPTOR.message_types_by_name['GetUserOrFriendsListInfoResponse'] = _GETUSERORFRIENDSLISTINFORESPONSE
DESCRIPTOR.message_types_by_name['UserOrFriendsListInfo'] = _USERORFRIENDSLISTINFO
DESCRIPTOR.message_types_by_name['UserOrFriendInfo'] = _USERORFRIENDINFO

class GetUserOrFriendsListInfoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETUSERORFRIENDSLISTINFOREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.hall.GetUserOrFriendsListInfo.GetUserOrFriendsListInfoRequest)

class GetUserOrFriendsListInfoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETUSERORFRIENDSLISTINFORESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.hall.GetUserOrFriendsListInfo.GetUserOrFriendsListInfoResponse)

class UserOrFriendsListInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERORFRIENDSLISTINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendsListInfo)

class UserOrFriendInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERORFRIENDINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.hall.GetUserOrFriendsListInfo.UserOrFriendInfo)

# @@protoc_insertion_point(module_scope)
