# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/hall/InviteJoinGroupAccept.proto',
  package='protoFile.hall.InviteJoinGroupAccept',
  serialized_pb='\n*protoFile/hall/InviteJoinGroupAccept.proto\x12$protoFile.hall.InviteJoinGroupAccept\"\\\n\x1cInviteJoinGroupAcceptRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x10\n\x08inviteId\x18\x02 \x02(\x05\x12\x0e\n\x06\x61reaId\x18\x03 \x02(\x05\x12\x0e\n\x06roomId\x18\x04 \x02(\x05\"@\n\x1dInviteJoinGroupAcceptResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_INVITEJOINGROUPACCEPTREQUEST = descriptor.Descriptor(
  name='InviteJoinGroupAcceptRequest',
  full_name='protoFile.hall.InviteJoinGroupAccept.InviteJoinGroupAcceptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.hall.InviteJoinGroupAccept.InviteJoinGroupAcceptRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inviteId', full_name='protoFile.hall.InviteJoinGroupAccept.InviteJoinGroupAcceptRequest.inviteId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='areaId', full_name='protoFile.hall.InviteJoinGroupAccept.InviteJoinGroupAcceptRequest.areaId', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roomId', full_name='protoFile.hall.InviteJoinGroupAccept.InviteJoinGroupAcceptRequest.roomId', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=84,
  serialized_end=176,
)


_INVITEJOINGROUPACCEPTRESPONSE = descriptor.Descriptor(
  name='InviteJoinGroupAcceptResponse',
  full_name='protoFile.hall.InviteJoinGroupAccept.InviteJoinGroupAcceptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.hall.InviteJoinGroupAccept.InviteJoinGroupAcceptResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.hall.InviteJoinGroupAccept.InviteJoinGroupAcceptResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=178,
  serialized_end=242,
)

DESCRIPTOR.message_types_by_name['InviteJoinGroupAcceptRequest'] = _INVITEJOINGROUPACCEPTREQUEST
DESCRIPTOR.message_types_by_name['InviteJoinGroupAcceptResponse'] = _INVITEJOINGROUPACCEPTRESPONSE

class InviteJoinGroupAcceptRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVITEJOINGROUPACCEPTREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.hall.InviteJoinGroupAccept.InviteJoinGroupAcceptRequest)

class InviteJoinGroupAcceptResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVITEJOINGROUPACCEPTRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.hall.InviteJoinGroupAccept.InviteJoinGroupAcceptResponse)

# @@protoc_insertion_point(module_scope)
