# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/nobility/GetWeiWangInfo3303.proto',
  package='protoFile.nobility.GetWeiWangInfo3303',
  serialized_pb='\n+protoFile/nobility/GetWeiWangInfo3303.proto\x12%protoFile.nobility.GetWeiWangInfo3303\"#\n\x15GetWeiWangInfoRequest\x12\n\n\x02id\x18\x01 \x02(\x05\"u\n\x16GetWeiWangInfoResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12:\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32,.protoFile.nobility.GetWeiWangInfo3303.Itemt\"A\n\x05Itemt\x12\x38\n\x02wp\x18\x01 \x03(\x0b\x32,.protoFile.nobility.GetWeiWangInfo3303.Wupin\"m\n\x05Wupin\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\x0f\n\x07weiwang\x18\x04 \x01(\x05\x12\r\n\x05\x61\x64\x64\x64q\x18\x05 \x01(\x08\x12\n\n\x02wy\x18\x06 \x01(\t\x12\x0f\n\x07\x61\x64\x64zuan\x18\x07 \x01(\x08')




_GETWEIWANGINFOREQUEST = descriptor.Descriptor(
  name='GetWeiWangInfoRequest',
  full_name='protoFile.nobility.GetWeiWangInfo3303.GetWeiWangInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.nobility.GetWeiWangInfo3303.GetWeiWangInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=86,
  serialized_end=121,
)


_GETWEIWANGINFORESPONSE = descriptor.Descriptor(
  name='GetWeiWangInfoResponse',
  full_name='protoFile.nobility.GetWeiWangInfo3303.GetWeiWangInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.nobility.GetWeiWangInfo3303.GetWeiWangInfoResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.nobility.GetWeiWangInfo3303.GetWeiWangInfoResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='protoFile.nobility.GetWeiWangInfo3303.GetWeiWangInfoResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=123,
  serialized_end=240,
)


_ITEMT = descriptor.Descriptor(
  name='Itemt',
  full_name='protoFile.nobility.GetWeiWangInfo3303.Itemt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='wp', full_name='protoFile.nobility.GetWeiWangInfo3303.Itemt.wp', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=242,
  serialized_end=307,
)


_WUPIN = descriptor.Descriptor(
  name='Wupin',
  full_name='protoFile.nobility.GetWeiWangInfo3303.Wupin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.nobility.GetWeiWangInfo3303.Wupin.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='protoFile.nobility.GetWeiWangInfo3303.Wupin.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='protoFile.nobility.GetWeiWangInfo3303.Wupin.count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='weiwang', full_name='protoFile.nobility.GetWeiWangInfo3303.Wupin.weiwang', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='adddq', full_name='protoFile.nobility.GetWeiWangInfo3303.Wupin.adddq', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wy', full_name='protoFile.nobility.GetWeiWangInfo3303.Wupin.wy', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='addzuan', full_name='protoFile.nobility.GetWeiWangInfo3303.Wupin.addzuan', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=309,
  serialized_end=418,
)

_GETWEIWANGINFORESPONSE.fields_by_name['data'].message_type = _ITEMT
_ITEMT.fields_by_name['wp'].message_type = _WUPIN
DESCRIPTOR.message_types_by_name['GetWeiWangInfoRequest'] = _GETWEIWANGINFOREQUEST
DESCRIPTOR.message_types_by_name['GetWeiWangInfoResponse'] = _GETWEIWANGINFORESPONSE
DESCRIPTOR.message_types_by_name['Itemt'] = _ITEMT
DESCRIPTOR.message_types_by_name['Wupin'] = _WUPIN

class GetWeiWangInfoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETWEIWANGINFOREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.nobility.GetWeiWangInfo3303.GetWeiWangInfoRequest)

class GetWeiWangInfoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETWEIWANGINFORESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.nobility.GetWeiWangInfo3303.GetWeiWangInfoResponse)

class Itemt(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ITEMT
  
  # @@protoc_insertion_point(class_scope:protoFile.nobility.GetWeiWangInfo3303.Itemt)

class Wupin(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WUPIN
  
  # @@protoc_insertion_point(class_scope:protoFile.nobility.GetWeiWangInfo3303.Wupin)

# @@protoc_insertion_point(module_scope)
