import beginners
import chat_net
import defence_net
import drinkery
import fight
import friend
import guild
import hall
import instance_net
import instanceColonize_net
import lodge
import login
import loginout
import mail
import map
import packageInfo
import pet
import playerInfo
import practice
import quest
import scence
import shop
import skill
import strengthen_net
import team
import toplist
import entrance
import award
import afk
import activation
import meditation
import schedule
import godhead
import nobility_net
import mosaic
import compound
import fate
import arena
import vipinfo
import gatetime_net
import pray_net
import tower
import zudui_net
import campaign
import zhanyi