# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/shop/buyItemInMall.proto',
  package='protoFile.shop.buyItemInMall',
  serialized_pb='\n\"protoFile/shop/buyItemInMall.proto\x12\x1cprotoFile.shop.buyItemInMall\"\\\n\x14\x62uyItemInMallRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x16\n\x0eitemTemplateId\x18\x02 \x02(\x05\x12\r\n\x05\x63ount\x18\x03 \x02(\x05\x12\x11\n\tpriceType\x18\x04 \x02(\x05\"r\n\x15\x62uyItemInMallResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x38\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32*.protoFile.shop.buyItemInMall.ResponseData\"Z\n\x0cResponseData\x12\x10\n\x08recharge\x18\x01 \x01(\x08\x12\x11\n\tpriceType\x18\x14 \x01(\x05\x12\x16\n\x0eitemTemplateId\x18\x03 \x02(\x05\x12\r\n\x05\x63ount\x18\x04 \x02(\x05')




_BUYITEMINMALLREQUEST = descriptor.Descriptor(
  name='buyItemInMallRequest',
  full_name='protoFile.shop.buyItemInMall.buyItemInMallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.shop.buyItemInMall.buyItemInMallRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='itemTemplateId', full_name='protoFile.shop.buyItemInMall.buyItemInMallRequest.itemTemplateId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='protoFile.shop.buyItemInMall.buyItemInMallRequest.count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='priceType', full_name='protoFile.shop.buyItemInMall.buyItemInMallRequest.priceType', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=160,
)


_BUYITEMINMALLRESPONSE = descriptor.Descriptor(
  name='buyItemInMallResponse',
  full_name='protoFile.shop.buyItemInMall.buyItemInMallResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.shop.buyItemInMall.buyItemInMallResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.shop.buyItemInMall.buyItemInMallResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='protoFile.shop.buyItemInMall.buyItemInMallResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=162,
  serialized_end=276,
)


_RESPONSEDATA = descriptor.Descriptor(
  name='ResponseData',
  full_name='protoFile.shop.buyItemInMall.ResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='recharge', full_name='protoFile.shop.buyItemInMall.ResponseData.recharge', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='priceType', full_name='protoFile.shop.buyItemInMall.ResponseData.priceType', index=1,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='itemTemplateId', full_name='protoFile.shop.buyItemInMall.ResponseData.itemTemplateId', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='protoFile.shop.buyItemInMall.ResponseData.count', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=278,
  serialized_end=368,
)

_BUYITEMINMALLRESPONSE.fields_by_name['data'].message_type = _RESPONSEDATA
DESCRIPTOR.message_types_by_name['buyItemInMallRequest'] = _BUYITEMINMALLREQUEST
DESCRIPTOR.message_types_by_name['buyItemInMallResponse'] = _BUYITEMINMALLRESPONSE
DESCRIPTOR.message_types_by_name['ResponseData'] = _RESPONSEDATA

class buyItemInMallRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BUYITEMINMALLREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.shop.buyItemInMall.buyItemInMallRequest)

class buyItemInMallResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BUYITEMINMALLRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.shop.buyItemInMall.buyItemInMallResponse)

class ResponseData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSEDATA
  
  # @@protoc_insertion_point(class_scope:protoFile.shop.buyItemInMall.ResponseData)

# @@protoc_insertion_point(module_scope)
