# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/revive/playerReviveInPlace.proto',
  package='protoFile.revive.playerReviveInPlace',
  serialized_pb='\n*protoFile/revive/playerReviveInPlace.proto\x12$protoFile.revive.playerReviveInPlace\"(\n\x1aplayerReviveInPlaceRequest\x12\n\n\x02id\x18\x01 \x02(\x05\">\n\x1bplayerReviveInPlaceResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_PLAYERREVIVEINPLACEREQUEST = descriptor.Descriptor(
  name='playerReviveInPlaceRequest',
  full_name='protoFile.revive.playerReviveInPlace.playerReviveInPlaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.revive.playerReviveInPlace.playerReviveInPlaceRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=84,
  serialized_end=124,
)


_PLAYERREVIVEINPLACERESPONSE = descriptor.Descriptor(
  name='playerReviveInPlaceResponse',
  full_name='protoFile.revive.playerReviveInPlace.playerReviveInPlaceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.revive.playerReviveInPlace.playerReviveInPlaceResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.revive.playerReviveInPlace.playerReviveInPlaceResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=126,
  serialized_end=188,
)

DESCRIPTOR.message_types_by_name['playerReviveInPlaceRequest'] = _PLAYERREVIVEINPLACEREQUEST
DESCRIPTOR.message_types_by_name['playerReviveInPlaceResponse'] = _PLAYERREVIVEINPLACERESPONSE

class playerReviveInPlaceRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERREVIVEINPLACEREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.revive.playerReviveInPlace.playerReviveInPlaceRequest)

class playerReviveInPlaceResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERREVIVEINPLACERESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.revive.playerReviveInPlace.playerReviveInPlaceResponse)

# @@protoc_insertion_point(module_scope)
