# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/schedule/GetTargetInfo3203.proto',
  package='protoFile.schedule.GetTargetInfo3203',
  serialized_pb='\n*protoFile/schedule/GetTargetInfo3203.proto\x12$protoFile.schedule.GetTargetInfo3203\"\"\n\x14GetTargetInfoRequest\x12\n\n\x02id\x18\x01 \x02(\x05\"\x80\x01\n\x15GetTargetInfoResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x46\n\x0b\x64\x61yTaskInfo\x18\x03 \x03(\x0b\x32\x31.protoFile.schedule.GetTargetInfo3203.DayTaskInfo\"\x84\x01\n\x0b\x44\x61yTaskInfo\x12\x11\n\tisSucFlag\x18\x01 \x01(\x08\x12N\n\x0f\x64\x61yListTaskInfo\x18\x02 \x03(\x0b\x32\x35.protoFile.schedule.GetTargetInfo3203.DayListTaskInfo\x12\x12\n\nisOpenFlag\x18\x03 \x01(\x08\"\xb4\x01\n\x0f\x44\x61yListTaskInfo\x12\x0e\n\x06taskId\x18\x01 \x01(\x05\x12\x16\n\x0eisCompleteFlag\x18\x02 \x01(\x08\x12\x0c\n\x04icon\x18\x03 \x01(\t\x12\x0f\n\x07taskDes\x18\x04 \x01(\t\x12\x14\n\x0cisObtainFlag\x18\x05 \x01(\x08\x12\x44\n\nrewardInfo\x18\x06 \x03(\x0b\x32\x30.protoFile.schedule.GetTargetInfo3203.RewardInfo\"[\n\nRewardInfo\x12\x0e\n\x06itemId\x18\x01 \x01(\x05\x12\x0c\n\x04icon\x18\x02 \x01(\x05\x12\r\n\x05stack\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x12\n\nrewardType\x18\x05 \x01(\x05')




_GETTARGETINFOREQUEST = descriptor.Descriptor(
  name='GetTargetInfoRequest',
  full_name='protoFile.schedule.GetTargetInfo3203.GetTargetInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.schedule.GetTargetInfo3203.GetTargetInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=84,
  serialized_end=118,
)


_GETTARGETINFORESPONSE = descriptor.Descriptor(
  name='GetTargetInfoResponse',
  full_name='protoFile.schedule.GetTargetInfo3203.GetTargetInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.schedule.GetTargetInfo3203.GetTargetInfoResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.schedule.GetTargetInfo3203.GetTargetInfoResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dayTaskInfo', full_name='protoFile.schedule.GetTargetInfo3203.GetTargetInfoResponse.dayTaskInfo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=121,
  serialized_end=249,
)


_DAYTASKINFO = descriptor.Descriptor(
  name='DayTaskInfo',
  full_name='protoFile.schedule.GetTargetInfo3203.DayTaskInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='isSucFlag', full_name='protoFile.schedule.GetTargetInfo3203.DayTaskInfo.isSucFlag', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dayListTaskInfo', full_name='protoFile.schedule.GetTargetInfo3203.DayTaskInfo.dayListTaskInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isOpenFlag', full_name='protoFile.schedule.GetTargetInfo3203.DayTaskInfo.isOpenFlag', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=252,
  serialized_end=384,
)


_DAYLISTTASKINFO = descriptor.Descriptor(
  name='DayListTaskInfo',
  full_name='protoFile.schedule.GetTargetInfo3203.DayListTaskInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='taskId', full_name='protoFile.schedule.GetTargetInfo3203.DayListTaskInfo.taskId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isCompleteFlag', full_name='protoFile.schedule.GetTargetInfo3203.DayListTaskInfo.isCompleteFlag', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='icon', full_name='protoFile.schedule.GetTargetInfo3203.DayListTaskInfo.icon', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='taskDes', full_name='protoFile.schedule.GetTargetInfo3203.DayListTaskInfo.taskDes', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isObtainFlag', full_name='protoFile.schedule.GetTargetInfo3203.DayListTaskInfo.isObtainFlag', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rewardInfo', full_name='protoFile.schedule.GetTargetInfo3203.DayListTaskInfo.rewardInfo', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=387,
  serialized_end=567,
)


_REWARDINFO = descriptor.Descriptor(
  name='RewardInfo',
  full_name='protoFile.schedule.GetTargetInfo3203.RewardInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='itemId', full_name='protoFile.schedule.GetTargetInfo3203.RewardInfo.itemId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='icon', full_name='protoFile.schedule.GetTargetInfo3203.RewardInfo.icon', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stack', full_name='protoFile.schedule.GetTargetInfo3203.RewardInfo.stack', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='protoFile.schedule.GetTargetInfo3203.RewardInfo.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rewardType', full_name='protoFile.schedule.GetTargetInfo3203.RewardInfo.rewardType', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=569,
  serialized_end=660,
)

_GETTARGETINFORESPONSE.fields_by_name['dayTaskInfo'].message_type = _DAYTASKINFO
_DAYTASKINFO.fields_by_name['dayListTaskInfo'].message_type = _DAYLISTTASKINFO
_DAYLISTTASKINFO.fields_by_name['rewardInfo'].message_type = _REWARDINFO
DESCRIPTOR.message_types_by_name['GetTargetInfoRequest'] = _GETTARGETINFOREQUEST
DESCRIPTOR.message_types_by_name['GetTargetInfoResponse'] = _GETTARGETINFORESPONSE
DESCRIPTOR.message_types_by_name['DayTaskInfo'] = _DAYTASKINFO
DESCRIPTOR.message_types_by_name['DayListTaskInfo'] = _DAYLISTTASKINFO
DESCRIPTOR.message_types_by_name['RewardInfo'] = _REWARDINFO

class GetTargetInfoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETTARGETINFOREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.schedule.GetTargetInfo3203.GetTargetInfoRequest)

class GetTargetInfoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETTARGETINFORESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.schedule.GetTargetInfo3203.GetTargetInfoResponse)

class DayTaskInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DAYTASKINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.schedule.GetTargetInfo3203.DayTaskInfo)

class DayListTaskInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DAYLISTTASKINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.schedule.GetTargetInfo3203.DayListTaskInfo)

class RewardInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REWARDINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.schedule.GetTargetInfo3203.RewardInfo)

# @@protoc_insertion_point(module_scope)
