# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/campaign/AutoJoinBattle4408.proto',
  package='protoFile.campaign.AutoJoinBattle4408',
  serialized_pb='\n+protoFile/campaign/AutoJoinBattle4408.proto\x12%protoFile.campaign.AutoJoinBattle4408\"9\n\x15\x41utoJoinBattleRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x14\n\x0c\x61utoJoinFlag\x18\x02 \x02(\x08\"9\n\x16\x41utoJoinBattleResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08')




_AUTOJOINBATTLEREQUEST = descriptor.Descriptor(
  name='AutoJoinBattleRequest',
  full_name='protoFile.campaign.AutoJoinBattle4408.AutoJoinBattleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.campaign.AutoJoinBattle4408.AutoJoinBattleRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='autoJoinFlag', full_name='protoFile.campaign.AutoJoinBattle4408.AutoJoinBattleRequest.autoJoinFlag', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=86,
  serialized_end=143,
)


_AUTOJOINBATTLERESPONSE = descriptor.Descriptor(
  name='AutoJoinBattleResponse',
  full_name='protoFile.campaign.AutoJoinBattle4408.AutoJoinBattleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.campaign.AutoJoinBattle4408.AutoJoinBattleResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.campaign.AutoJoinBattle4408.AutoJoinBattleResponse.result', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=145,
  serialized_end=202,
)

DESCRIPTOR.message_types_by_name['AutoJoinBattleRequest'] = _AUTOJOINBATTLEREQUEST
DESCRIPTOR.message_types_by_name['AutoJoinBattleResponse'] = _AUTOJOINBATTLERESPONSE

class AutoJoinBattleRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTOJOINBATTLEREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.campaign.AutoJoinBattle4408.AutoJoinBattleRequest)

class AutoJoinBattleResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTOJOINBATTLERESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.campaign.AutoJoinBattle4408.AutoJoinBattleResponse)

# @@protoc_insertion_point(module_scope)
