# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/campaign/GroupPK4403.proto',
  package='protoFile.campaign.GroupPK4403',
  serialized_pb='\n$protoFile/campaign/GroupPK4403.proto\x12\x1eprotoFile.campaign.GroupPK4403\"*\n\x0eGroupPKRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04pkId\x18\x02 \x02(\x05\"2\n\x0fGroupPKResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08')




_GROUPPKREQUEST = descriptor.Descriptor(
  name='GroupPKRequest',
  full_name='protoFile.campaign.GroupPK4403.GroupPKRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.campaign.GroupPK4403.GroupPKRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pkId', full_name='protoFile.campaign.GroupPK4403.GroupPKRequest.pkId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=72,
  serialized_end=114,
)


_GROUPPKRESPONSE = descriptor.Descriptor(
  name='GroupPKResponse',
  full_name='protoFile.campaign.GroupPK4403.GroupPKResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.campaign.GroupPK4403.GroupPKResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.campaign.GroupPK4403.GroupPKResponse.result', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=116,
  serialized_end=166,
)

DESCRIPTOR.message_types_by_name['GroupPKRequest'] = _GROUPPKREQUEST
DESCRIPTOR.message_types_by_name['GroupPKResponse'] = _GROUPPKRESPONSE

class GroupPKRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GROUPPKREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.campaign.GroupPK4403.GroupPKRequest)

class GroupPKResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GROUPPKRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.campaign.GroupPK4403.GroupPKResponse)

# @@protoc_insertion_point(module_scope)
