# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/guild/FaminlyLevelUp.proto',
  package='protoFile.guild.FaminlyLevelUp',
  serialized_pb='\n$protoFile/guild/FaminlyLevelUp.proto\x12\x1eprotoFile.guild.FaminlyLevelUp\"\"\n\x14\x46\x61milyLevelUpRequest\x12\n\n\x02id\x18\x01 \x02(\x05\"8\n\x15\x46\x61milyLevelUpResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_FAMILYLEVELUPREQUEST = descriptor.Descriptor(
  name='FamilyLevelUpRequest',
  full_name='protoFile.guild.FaminlyLevelUp.FamilyLevelUpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.guild.FaminlyLevelUp.FamilyLevelUpRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=72,
  serialized_end=106,
)


_FAMILYLEVELUPRESPONSE = descriptor.Descriptor(
  name='FamilyLevelUpResponse',
  full_name='protoFile.guild.FaminlyLevelUp.FamilyLevelUpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.guild.FaminlyLevelUp.FamilyLevelUpResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.guild.FaminlyLevelUp.FamilyLevelUpResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=108,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['FamilyLevelUpRequest'] = _FAMILYLEVELUPREQUEST
DESCRIPTOR.message_types_by_name['FamilyLevelUpResponse'] = _FAMILYLEVELUPRESPONSE

class FamilyLevelUpRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FAMILYLEVELUPREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.guild.FaminlyLevelUp.FamilyLevelUpRequest)

class FamilyLevelUpResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FAMILYLEVELUPRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.guild.FaminlyLevelUp.FamilyLevelUpResponse)

# @@protoc_insertion_point(module_scope)
