# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/guild/GetCorpsTechnologyListInfo.proto',
  package='protoFile.guild.GetCorpsTechnologyListInfo',
  serialized_pb='\n0protoFile/guild/GetCorpsTechnologyListInfo.proto\x12*protoFile.guild.GetCorpsTechnologyListInfo\"@\n!GetCorpsTechnologyListInfoRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07\x63urPage\x18\x02 \x02(\x05\"\x94\x01\n\"GetCorpsTechnologyListInfoResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12M\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32?.protoFile.guild.GetCorpsTechnologyListInfo.CorpsTechnologyInfo\"\x8b\x01\n\x13\x43orpsTechnologyInfo\x12\x0f\n\x07\x63urPage\x18\x01 \x01(\x05\x12\x0f\n\x07maxPage\x18\x02 \x01(\x05\x12R\n\x0etechnologyInfo\x18\x03 \x03(\x0b\x32:.protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo\"\xdf\x01\n\x0eTechnologyInfo\x12\x14\n\x0ctechnologyId\x18\x01 \x01(\x05\x12\x15\n\rtechnologyImg\x18\x02 \x01(\x05\x12\x16\n\x0etechnologyName\x18\x03 \x01(\t\x12\x17\n\x0ftechnologyLevel\x18\x04 \x01(\x05\x12\x17\n\x0fremainCondition\x18\x05 \x01(\t\x12\x13\n\x0b\x63urSchedule\x18\x06 \x01(\x05\x12\x13\n\x0bmaxSchedule\x18\x07 \x01(\x05\x12\x15\n\rtechnologyDes\x18\x08 \x01(\t\x12\x15\n\rdefaultDonate\x18\t \x01(\x08')




_GETCORPSTECHNOLOGYLISTINFOREQUEST = descriptor.Descriptor(
  name='GetCorpsTechnologyListInfoRequest',
  full_name='protoFile.guild.GetCorpsTechnologyListInfo.GetCorpsTechnologyListInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.guild.GetCorpsTechnologyListInfo.GetCorpsTechnologyListInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='curPage', full_name='protoFile.guild.GetCorpsTechnologyListInfo.GetCorpsTechnologyListInfoRequest.curPage', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=96,
  serialized_end=160,
)


_GETCORPSTECHNOLOGYLISTINFORESPONSE = descriptor.Descriptor(
  name='GetCorpsTechnologyListInfoResponse',
  full_name='protoFile.guild.GetCorpsTechnologyListInfo.GetCorpsTechnologyListInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.guild.GetCorpsTechnologyListInfo.GetCorpsTechnologyListInfoResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.guild.GetCorpsTechnologyListInfo.GetCorpsTechnologyListInfoResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='protoFile.guild.GetCorpsTechnologyListInfo.GetCorpsTechnologyListInfoResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=163,
  serialized_end=311,
)


_CORPSTECHNOLOGYINFO = descriptor.Descriptor(
  name='CorpsTechnologyInfo',
  full_name='protoFile.guild.GetCorpsTechnologyListInfo.CorpsTechnologyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='curPage', full_name='protoFile.guild.GetCorpsTechnologyListInfo.CorpsTechnologyInfo.curPage', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='maxPage', full_name='protoFile.guild.GetCorpsTechnologyListInfo.CorpsTechnologyInfo.maxPage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='technologyInfo', full_name='protoFile.guild.GetCorpsTechnologyListInfo.CorpsTechnologyInfo.technologyInfo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=314,
  serialized_end=453,
)


_TECHNOLOGYINFO = descriptor.Descriptor(
  name='TechnologyInfo',
  full_name='protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='technologyId', full_name='protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo.technologyId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='technologyImg', full_name='protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo.technologyImg', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='technologyName', full_name='protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo.technologyName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='technologyLevel', full_name='protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo.technologyLevel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='remainCondition', full_name='protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo.remainCondition', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='curSchedule', full_name='protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo.curSchedule', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='maxSchedule', full_name='protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo.maxSchedule', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='technologyDes', full_name='protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo.technologyDes', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='defaultDonate', full_name='protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo.defaultDonate', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=456,
  serialized_end=679,
)

_GETCORPSTECHNOLOGYLISTINFORESPONSE.fields_by_name['data'].message_type = _CORPSTECHNOLOGYINFO
_CORPSTECHNOLOGYINFO.fields_by_name['technologyInfo'].message_type = _TECHNOLOGYINFO
DESCRIPTOR.message_types_by_name['GetCorpsTechnologyListInfoRequest'] = _GETCORPSTECHNOLOGYLISTINFOREQUEST
DESCRIPTOR.message_types_by_name['GetCorpsTechnologyListInfoResponse'] = _GETCORPSTECHNOLOGYLISTINFORESPONSE
DESCRIPTOR.message_types_by_name['CorpsTechnologyInfo'] = _CORPSTECHNOLOGYINFO
DESCRIPTOR.message_types_by_name['TechnologyInfo'] = _TECHNOLOGYINFO

class GetCorpsTechnologyListInfoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETCORPSTECHNOLOGYLISTINFOREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.guild.GetCorpsTechnologyListInfo.GetCorpsTechnologyListInfoRequest)

class GetCorpsTechnologyListInfoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETCORPSTECHNOLOGYLISTINFORESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.guild.GetCorpsTechnologyListInfo.GetCorpsTechnologyListInfoResponse)

class CorpsTechnologyInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CORPSTECHNOLOGYINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.guild.GetCorpsTechnologyListInfo.CorpsTechnologyInfo)

class TechnologyInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TECHNOLOGYINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.guild.GetCorpsTechnologyListInfo.TechnologyInfo)

# @@protoc_insertion_point(module_scope)
