# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/guild/ModifyCorpsAnnoun.proto',
  package='protoFile.guild.ModifyCorpsAnnoun',
  serialized_pb='\n\'protoFile/guild/ModifyCorpsAnnoun.proto\x12!protoFile.guild.ModifyCorpsAnnoun\"N\n\x18ModifyCorpsAnnounRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07\x63orpsId\x18\x02 \x02(\x05\x12\x15\n\rannounContent\x18\x03 \x02(\t\"<\n\x19ModifyCorpsAnnounResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_MODIFYCORPSANNOUNREQUEST = descriptor.Descriptor(
  name='ModifyCorpsAnnounRequest',
  full_name='protoFile.guild.ModifyCorpsAnnoun.ModifyCorpsAnnounRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.guild.ModifyCorpsAnnoun.ModifyCorpsAnnounRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='corpsId', full_name='protoFile.guild.ModifyCorpsAnnoun.ModifyCorpsAnnounRequest.corpsId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='announContent', full_name='protoFile.guild.ModifyCorpsAnnoun.ModifyCorpsAnnounRequest.announContent', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=156,
)


_MODIFYCORPSANNOUNRESPONSE = descriptor.Descriptor(
  name='ModifyCorpsAnnounResponse',
  full_name='protoFile.guild.ModifyCorpsAnnoun.ModifyCorpsAnnounResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.guild.ModifyCorpsAnnoun.ModifyCorpsAnnounResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.guild.ModifyCorpsAnnoun.ModifyCorpsAnnounResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=158,
  serialized_end=218,
)

DESCRIPTOR.message_types_by_name['ModifyCorpsAnnounRequest'] = _MODIFYCORPSANNOUNREQUEST
DESCRIPTOR.message_types_by_name['ModifyCorpsAnnounResponse'] = _MODIFYCORPSANNOUNRESPONSE

class ModifyCorpsAnnounRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODIFYCORPSANNOUNREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.guild.ModifyCorpsAnnoun.ModifyCorpsAnnounRequest)

class ModifyCorpsAnnounResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODIFYCORPSANNOUNRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.guild.ModifyCorpsAnnoun.ModifyCorpsAnnounResponse)

# @@protoc_insertion_point(module_scope)
