# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/defence/GetRewardBattleInfo2404.proto',
  package='protoFile.defence.GetRewardBattleInfo2404',
  serialized_pb='\n/protoFile/defence/GetRewardBattleInfo2404.proto\x12)protoFile.defence.GetRewardBattleInfo2404\"D\n\x1aGetRewardBattleInfoRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04r_id\x18\x02 \x02(\x05\x12\x0c\n\x04page\x18\x03 \x02(\x05\"\x91\x01\n\x1bGetRewardBattleInfoResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12Q\n\x0e\x62\x61ttleListInfo\x18\x03 \x01(\x0b\x32\x39.protoFile.defence.GetRewardBattleInfo2404.BattleListInfo\"\x8b\x01\n\x0e\x42\x61ttleListInfo\x12\x0c\n\x04r_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63urPage\x18\x02 \x01(\x05\x12\x0f\n\x07maxPage\x18\x03 \x01(\x05\x12I\n\nbattleInfo\x18\x04 \x03(\x0b\x32\x35.protoFile.defence.GetRewardBattleInfo2404.BattleInfo\"\xd7\x01\n\nBattleInfo\x12\x12\n\nbattleName\x18\x01 \x01(\t\x12\x14\n\x0c\x62\x61ttleResult\x18\x02 \x01(\x08\x12N\n\x0bsucRoleInfo\x18\x03 \x03(\x0b\x32\x39.protoFile.defence.GetRewardBattleInfo2404.BattleRoleInfo\x12O\n\x0c\x66\x61ilRoleInfo\x18\x04 \x03(\x0b\x32\x39.protoFile.defence.GetRewardBattleInfo2404.BattleRoleInfo\"2\n\x0e\x42\x61ttleRoleInfo\x12\x0e\n\x06roleId\x18\x01 \x01(\x05\x12\x10\n\x08roleName\x18\x02 \x01(\t')




_GETREWARDBATTLEINFOREQUEST = descriptor.Descriptor(
  name='GetRewardBattleInfoRequest',
  full_name='protoFile.defence.GetRewardBattleInfo2404.GetRewardBattleInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.defence.GetRewardBattleInfo2404.GetRewardBattleInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='r_id', full_name='protoFile.defence.GetRewardBattleInfo2404.GetRewardBattleInfoRequest.r_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='page', full_name='protoFile.defence.GetRewardBattleInfo2404.GetRewardBattleInfoRequest.page', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=94,
  serialized_end=162,
)


_GETREWARDBATTLEINFORESPONSE = descriptor.Descriptor(
  name='GetRewardBattleInfoResponse',
  full_name='protoFile.defence.GetRewardBattleInfo2404.GetRewardBattleInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.defence.GetRewardBattleInfo2404.GetRewardBattleInfoResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.defence.GetRewardBattleInfo2404.GetRewardBattleInfoResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='battleListInfo', full_name='protoFile.defence.GetRewardBattleInfo2404.GetRewardBattleInfoResponse.battleListInfo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=165,
  serialized_end=310,
)


_BATTLELISTINFO = descriptor.Descriptor(
  name='BattleListInfo',
  full_name='protoFile.defence.GetRewardBattleInfo2404.BattleListInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='r_id', full_name='protoFile.defence.GetRewardBattleInfo2404.BattleListInfo.r_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='curPage', full_name='protoFile.defence.GetRewardBattleInfo2404.BattleListInfo.curPage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='maxPage', full_name='protoFile.defence.GetRewardBattleInfo2404.BattleListInfo.maxPage', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='battleInfo', full_name='protoFile.defence.GetRewardBattleInfo2404.BattleListInfo.battleInfo', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=313,
  serialized_end=452,
)


_BATTLEINFO = descriptor.Descriptor(
  name='BattleInfo',
  full_name='protoFile.defence.GetRewardBattleInfo2404.BattleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='battleName', full_name='protoFile.defence.GetRewardBattleInfo2404.BattleInfo.battleName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='battleResult', full_name='protoFile.defence.GetRewardBattleInfo2404.BattleInfo.battleResult', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sucRoleInfo', full_name='protoFile.defence.GetRewardBattleInfo2404.BattleInfo.sucRoleInfo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='failRoleInfo', full_name='protoFile.defence.GetRewardBattleInfo2404.BattleInfo.failRoleInfo', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=455,
  serialized_end=670,
)


_BATTLEROLEINFO = descriptor.Descriptor(
  name='BattleRoleInfo',
  full_name='protoFile.defence.GetRewardBattleInfo2404.BattleRoleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='roleId', full_name='protoFile.defence.GetRewardBattleInfo2404.BattleRoleInfo.roleId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='roleName', full_name='protoFile.defence.GetRewardBattleInfo2404.BattleRoleInfo.roleName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=672,
  serialized_end=722,
)

_GETREWARDBATTLEINFORESPONSE.fields_by_name['battleListInfo'].message_type = _BATTLELISTINFO
_BATTLELISTINFO.fields_by_name['battleInfo'].message_type = _BATTLEINFO
_BATTLEINFO.fields_by_name['sucRoleInfo'].message_type = _BATTLEROLEINFO
_BATTLEINFO.fields_by_name['failRoleInfo'].message_type = _BATTLEROLEINFO
DESCRIPTOR.message_types_by_name['GetRewardBattleInfoRequest'] = _GETREWARDBATTLEINFOREQUEST
DESCRIPTOR.message_types_by_name['GetRewardBattleInfoResponse'] = _GETREWARDBATTLEINFORESPONSE
DESCRIPTOR.message_types_by_name['BattleListInfo'] = _BATTLELISTINFO
DESCRIPTOR.message_types_by_name['BattleInfo'] = _BATTLEINFO
DESCRIPTOR.message_types_by_name['BattleRoleInfo'] = _BATTLEROLEINFO

class GetRewardBattleInfoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETREWARDBATTLEINFOREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.defence.GetRewardBattleInfo2404.GetRewardBattleInfoRequest)

class GetRewardBattleInfoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETREWARDBATTLEINFORESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.defence.GetRewardBattleInfo2404.GetRewardBattleInfoResponse)

class BattleListInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BATTLELISTINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.defence.GetRewardBattleInfo2404.BattleListInfo)

class BattleInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BATTLEINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.defence.GetRewardBattleInfo2404.BattleInfo)

class BattleRoleInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BATTLEROLEINFO
  
  # @@protoc_insertion_point(class_scope:protoFile.defence.GetRewardBattleInfo2404.BattleRoleInfo)

# @@protoc_insertion_point(module_scope)
