# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/defence/ObtainReward2402.proto',
  package='protoFile.defence.ObtainReward2402',
  serialized_pb='\n(protoFile/defence/ObtainReward2402.proto\x12\"protoFile.defence.ObtainReward2402\"/\n\x13ObtainRewardRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04r_id\x18\x02 \x02(\x05\"7\n\x14ObtainRewardResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_OBTAINREWARDREQUEST = descriptor.Descriptor(
  name='ObtainRewardRequest',
  full_name='protoFile.defence.ObtainReward2402.ObtainRewardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.defence.ObtainReward2402.ObtainRewardRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='r_id', full_name='protoFile.defence.ObtainReward2402.ObtainRewardRequest.r_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=80,
  serialized_end=127,
)


_OBTAINREWARDRESPONSE = descriptor.Descriptor(
  name='ObtainRewardResponse',
  full_name='protoFile.defence.ObtainReward2402.ObtainRewardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.defence.ObtainReward2402.ObtainRewardResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.defence.ObtainReward2402.ObtainRewardResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=129,
  serialized_end=184,
)

DESCRIPTOR.message_types_by_name['ObtainRewardRequest'] = _OBTAINREWARDREQUEST
DESCRIPTOR.message_types_by_name['ObtainRewardResponse'] = _OBTAINREWARDRESPONSE

class ObtainRewardRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OBTAINREWARDREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.defence.ObtainReward2402.ObtainRewardRequest)

class ObtainRewardResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OBTAINREWARDRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.defence.ObtainReward2402.ObtainRewardResponse)

# @@protoc_insertion_point(module_scope)
