# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/meditation/GetGuaJiInfo3201.proto',
  package='protoFile.meditation.GetGuaJiInfo3201',
  serialized_pb='\n+protoFile/meditation/GetGuaJiInfo3201.proto\x12%protoFile.meditation.GetGuaJiInfo3201\"!\n\x13GetGuaJiInfoRequest\x12\n\n\x02id\x18\x01 \x02(\x05\"l\n\x14GetGuaJiInfoResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06\x65xpStr\x18\x03 \x01(\t\x12\x11\n\tzhanliStr\x18\x04 \x01(\t\x12\x10\n\x08gujiTime\x18\x05 \x01(\x05')




_GETGUAJIINFOREQUEST = descriptor.Descriptor(
  name='GetGuaJiInfoRequest',
  full_name='protoFile.meditation.GetGuaJiInfo3201.GetGuaJiInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.meditation.GetGuaJiInfo3201.GetGuaJiInfoRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=86,
  serialized_end=119,
)


_GETGUAJIINFORESPONSE = descriptor.Descriptor(
  name='GetGuaJiInfoResponse',
  full_name='protoFile.meditation.GetGuaJiInfo3201.GetGuaJiInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.meditation.GetGuaJiInfo3201.GetGuaJiInfoResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.meditation.GetGuaJiInfo3201.GetGuaJiInfoResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='expStr', full_name='protoFile.meditation.GetGuaJiInfo3201.GetGuaJiInfoResponse.expStr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='zhanliStr', full_name='protoFile.meditation.GetGuaJiInfo3201.GetGuaJiInfoResponse.zhanliStr', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gujiTime', full_name='protoFile.meditation.GetGuaJiInfo3201.GetGuaJiInfoResponse.gujiTime', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=121,
  serialized_end=229,
)

DESCRIPTOR.message_types_by_name['GetGuaJiInfoRequest'] = _GETGUAJIINFOREQUEST
DESCRIPTOR.message_types_by_name['GetGuaJiInfoResponse'] = _GETGUAJIINFORESPONSE

class GetGuaJiInfoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETGUAJIINFOREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.meditation.GetGuaJiInfo3201.GetGuaJiInfoRequest)

class GetGuaJiInfoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETGUAJIINFORESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.meditation.GetGuaJiInfo3201.GetGuaJiInfoResponse)

# @@protoc_insertion_point(module_scope)
