# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/meditation/StartUpGuaJi3200.proto',
  package='protoFile.meditation.StartUpGuaJi3200',
  serialized_pb='\n+protoFile/meditation/StartUpGuaJi3200.proto\x12%protoFile.meditation.StartUpGuaJi3200\"!\n\x13StartUpGuaJiRequest\x12\n\n\x02id\x18\x01 \x02(\x05\"7\n\x14StartUpGuaJiResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_STARTUPGUAJIREQUEST = descriptor.Descriptor(
  name='StartUpGuaJiRequest',
  full_name='protoFile.meditation.StartUpGuaJi3200.StartUpGuaJiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.meditation.StartUpGuaJi3200.StartUpGuaJiRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=86,
  serialized_end=119,
)


_STARTUPGUAJIRESPONSE = descriptor.Descriptor(
  name='StartUpGuaJiResponse',
  full_name='protoFile.meditation.StartUpGuaJi3200.StartUpGuaJiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.meditation.StartUpGuaJi3200.StartUpGuaJiResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.meditation.StartUpGuaJi3200.StartUpGuaJiResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=121,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['StartUpGuaJiRequest'] = _STARTUPGUAJIREQUEST
DESCRIPTOR.message_types_by_name['StartUpGuaJiResponse'] = _STARTUPGUAJIRESPONSE

class StartUpGuaJiRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STARTUPGUAJIREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.meditation.StartUpGuaJi3200.StartUpGuaJiRequest)

class StartUpGuaJiResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STARTUPGUAJIRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.meditation.StartUpGuaJi3200.StartUpGuaJiResponse)

# @@protoc_insertion_point(module_scope)
