# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/mail/deleteMail.proto',
  package='protoFile.mail.deleteMail',
  serialized_pb='\n\x1fprotoFile/mail/deleteMail.proto\x12\x19protoFile.mail.deleteMail\"/\n\x11\x64\x65leteMailRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06mailId\x18\x02 \x02(\x05\"5\n\x12\x64\x65leteMailResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_DELETEMAILREQUEST = descriptor.Descriptor(
  name='deleteMailRequest',
  full_name='protoFile.mail.deleteMail.deleteMailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.mail.deleteMail.deleteMailRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mailId', full_name='protoFile.mail.deleteMail.deleteMailRequest.mailId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=62,
  serialized_end=109,
)


_DELETEMAILRESPONSE = descriptor.Descriptor(
  name='deleteMailResponse',
  full_name='protoFile.mail.deleteMail.deleteMailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.mail.deleteMail.deleteMailResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.mail.deleteMail.deleteMailResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=111,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['deleteMailRequest'] = _DELETEMAILREQUEST
DESCRIPTOR.message_types_by_name['deleteMailResponse'] = _DELETEMAILRESPONSE

class deleteMailRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEMAILREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.mail.deleteMail.deleteMailRequest)

class deleteMailResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETEMAILRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.mail.deleteMail.deleteMailResponse)

# @@protoc_insertion_point(module_scope)
