# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/packageInfo/packageArrange.proto',
  package='protoFile.packageInfo.packageArrange',
  serialized_pb='\n*protoFile/packageInfo/packageArrange.proto\x12$protoFile.packageInfo.packageArrange\"8\n\x15packageArrangeRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x13\n\x0bpackageType\x18\x02 \x02(\x05\"G\n\x16packageArrangeResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x05')




_PACKAGEARRANGEREQUEST = descriptor.Descriptor(
  name='packageArrangeRequest',
  full_name='protoFile.packageInfo.packageArrange.packageArrangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.packageInfo.packageArrange.packageArrangeRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='packageType', full_name='protoFile.packageInfo.packageArrange.packageArrangeRequest.packageType', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=84,
  serialized_end=140,
)


_PACKAGEARRANGERESPONSE = descriptor.Descriptor(
  name='packageArrangeResponse',
  full_name='protoFile.packageInfo.packageArrange.packageArrangeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.packageInfo.packageArrange.packageArrangeResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.packageInfo.packageArrange.packageArrangeResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='protoFile.packageInfo.packageArrange.packageArrangeResponse.data', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=142,
  serialized_end=213,
)

DESCRIPTOR.message_types_by_name['packageArrangeRequest'] = _PACKAGEARRANGEREQUEST
DESCRIPTOR.message_types_by_name['packageArrangeResponse'] = _PACKAGEARRANGERESPONSE

class packageArrangeRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKAGEARRANGEREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.packageInfo.packageArrange.packageArrangeRequest)

class packageArrangeResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKAGEARRANGERESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.packageInfo.packageArrange.packageArrangeResponse)

# @@protoc_insertion_point(module_scope)
