# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='protoFile/chat/ModifyChatSetting1006.proto',
  package='protoFile.chat.ModifyChatSetting1006',
  serialized_pb='\n*protoFile/chat/ModifyChatSetting1006.proto\x12$protoFile.chat.ModifyChatSetting1006\"\x8c\x01\n\x18ModifyChatSettingRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x10\n\x08systemCK\x18\x02 \x02(\x08\x12\x0e\n\x06showCK\x18\x03 \x02(\x08\x12\x10\n\x08\x63ommonCK\x18\x04 \x02(\x08\x12\x0f\n\x07groupCK\x18\x05 \x02(\x08\x12\x0f\n\x07\x63orpsCK\x18\x06 \x02(\x08\x12\x0e\n\x06selfCK\x18\x07 \x02(\x08\"<\n\x19ModifyChatSettingResponse\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t')




_MODIFYCHATSETTINGREQUEST = descriptor.Descriptor(
  name='ModifyChatSettingRequest',
  full_name='protoFile.chat.ModifyChatSetting1006.ModifyChatSettingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='protoFile.chat.ModifyChatSetting1006.ModifyChatSettingRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='systemCK', full_name='protoFile.chat.ModifyChatSetting1006.ModifyChatSettingRequest.systemCK', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='showCK', full_name='protoFile.chat.ModifyChatSetting1006.ModifyChatSettingRequest.showCK', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='commonCK', full_name='protoFile.chat.ModifyChatSetting1006.ModifyChatSettingRequest.commonCK', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='groupCK', full_name='protoFile.chat.ModifyChatSetting1006.ModifyChatSettingRequest.groupCK', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='corpsCK', full_name='protoFile.chat.ModifyChatSetting1006.ModifyChatSettingRequest.corpsCK', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='selfCK', full_name='protoFile.chat.ModifyChatSetting1006.ModifyChatSettingRequest.selfCK', index=6,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=85,
  serialized_end=225,
)


_MODIFYCHATSETTINGRESPONSE = descriptor.Descriptor(
  name='ModifyChatSettingResponse',
  full_name='protoFile.chat.ModifyChatSetting1006.ModifyChatSettingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='protoFile.chat.ModifyChatSetting1006.ModifyChatSettingResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protoFile.chat.ModifyChatSetting1006.ModifyChatSettingResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=227,
  serialized_end=287,
)

DESCRIPTOR.message_types_by_name['ModifyChatSettingRequest'] = _MODIFYCHATSETTINGREQUEST
DESCRIPTOR.message_types_by_name['ModifyChatSettingResponse'] = _MODIFYCHATSETTINGRESPONSE

class ModifyChatSettingRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODIFYCHATSETTINGREQUEST
  
  # @@protoc_insertion_point(class_scope:protoFile.chat.ModifyChatSetting1006.ModifyChatSettingRequest)

class ModifyChatSettingResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODIFYCHATSETTINGRESPONSE
  
  # @@protoc_insertion_point(class_scope:protoFile.chat.ModifyChatSetting1006.ModifyChatSettingResponse)

# @@protoc_insertion_point(module_scope)
